### ISSUE TITLE
Error "No appropriate version found" when installing

### ISSUE THREAD

**Issue by a13ph** [zhouhua/obsidian-sticky-headings#1]
"No appropriate version found" error notice when trying to install from Community Plugins list and plugin fails to install.

With BRAT it's fine - no errors, installation successful, settings page is available.

I am unsure what is this about, since there are no new messages in devtools console when installing this plugin via Community Plugins list.

**Comment by zhouhua** [comment]
Thank you for reporting this bug. I have now fixed the issue.
