### ISSUE TITLE
New Indent Level Attribute Fails on Heading Levels Below the First

### ISSUE THREAD

**Issue by itsonlyjames** [zhouhua/obsidian-sticky-headings#11]
This is likely easily fixed and just a simple JS miscalculation somewhere.

![image](https://github.com/user-attachments/assets/c57e29ad-6823-4099-b687-d97db0d890a3)
![image](https://github.com/user-attachments/assets/d24aa4ab-8cc4-4788-bbed-5d01e49ae8a0)

Hierarchy to reproduce this is:
```
## testing
### testing
#### testing
## testing (this gets indent level 0, should be 1)
### testing (this gets indent level 1, should be 2)
```

**Comment by zhouhua** [comment]
I made a mistake, just fixed it.
