### ISSUE TITLE
[Question] Rendering of Square Brackets in Sticky Items

### ISSUE THREAD

**Issue by itsonlyjames** [zhouhua/obsidian-sticky-headings#12]
More of a question than a bug, should we remove the square brackets from headings that are wikilinks?

![image](https://github.com/user-attachments/assets/7245207e-30ee-49e4-820c-0a124730804b)

Clicking on it obviously doesn't take you to the linked note, so for aestheics should we strip these?

**Comment by zhouhua** [comment]
Good question. Maybe I should transform markdown to html. Most cases should work fine, ecxept user put ordered list in heading.

**Comment by itsonlyjames** [comment]
I actually just had a go, check out this PR: https://github.com/zhouhua/obsidian-sticky-headings/pull/13
