### ISSUE TITLE
Sticky Headings Act Randomly in Floating Leafs

### ISSUE THREAD

**Issue by itsonlyjames** [zhouhua/obsidian-sticky-headings#16]
Sometimes they stick when changing between main window and floating window, however they do not seem to stick on scroll.

Steps to repro:
1. Move current tab to a new window
2. Scroll and observe no headings sticking

I think it is something to do with the leaf or active leaf that's being targetted. I notice you use `iterateLeaves`, whereas in my plugin I use `iterateAllLeaves` which also accesses floating leaves.

**Comment by zhouhua** [comment]
https://github.com/zhouhua/obsidian-sticky-headings/commit/26111d76630a3f21a176e17e89387086b5dbc32f I've fixed this issue.
