### ISSUE TITLE
Slow Addition and Removal of Headings in Popout Leaf (Compared to Main Window)

### ISSUE THREAD

**Issue by itsonlyjames** [zhouhua/obsidian-sticky-headings#18]
Popout leaf:
![sticky-popout-leaf](https://github.com/user-attachments/assets/97036995-b8a7-4c53-aea5-5fbfdbc6ae41)

Main leaf:
![sticky-main-window](https://github.com/user-attachments/assets/7363f413-38a1-40c0-8d20-bd793940b7ef)

**Comment by zhouhua** [comment]
Sorry, James. I haven't had much time to dedicate to this plugin's development lately, so my replies have been slow. 

For some reason, I couldn't reproduce the issue you're experiencing.

**Comment by itsonlyjames** [comment]
No worries @zhouhua. I started uni last week so been busy too. 

Your fix in https://github.com/zhouhua/obsidian-sticky-headings/commit/7f103667e684a3b0258ab40c4bc761fd7acd4e48 actually fixed this issue also. I was thinking it was related to iterating the leaves 👍 Nice one.
