### ISSUE TITLE
Will block search bar if it floats on the top area

### ISSUE THREAD

**Issue by lethefrost** [zhouhua/obsidian-sticky-headings#29]
For example, if you try out themes like [border](https://github.com/Akifyss/obsidian-border), it has a search bar floating on the top area. The sticky headings' container has a higher z index so it would obstruct the search bar and make it not focusable anymore.

**Comment by itsonlyjames** [comment]
This one's interesting! I thought for sure z-index could solve the issue but no the flow of the document means for some reason it won't change. So your fix does work, although it's not ideal, it is what it is and it fixes the issue!

**Comment by zhouhua** [comment]
I have released a new version, and this issue has been fixed.
