### ISSUE TITLE
Feature Request: Status Bar Mode

### ISSUE THREAD

**Issue by TheMathGuyd** [zhouhua/obsidian-sticky-headings#3]
In effort to reclaim more vertical space, I would like to see the sticky heading information in the status bar, rather than above each pane.

**Comment by zhouhua** [comment]
Isn't the space in the status bar too small? Or do you have any more specific ideas?

**Comment by zhouhua** [comment]
BTW, you can also reduce the number of displayed headings in the settings to save vertical space.

**Comment by TheMathGuyd** [comment]
I understand there is Concise Mode in settings. I would like that content displayed (with no line break) in the status bar. 
Many users hide elements in the status bar, and have lots unused of horizontal space.
I will attach an mock-up to show where I feel it could fit:
![Screenshot 2024-07-04 at 09 17 57](https://github.com/zhouhua/obsidian-sticky-headings/assets/85257386/6c2e78dd-d49e-4d69-a6f0-77630efd37b9)

**Comment by zhouhua** [comment]
If you're really concerned about the vertical space usage, you might want to try the Obsidian Floating TOC plugin. If this plugin still doesn't meet your expectations, we can then discuss whether to add the headings to the status bar.

**Comment by TheMathGuyd** [comment]
Thanks for suggesting an alternative. I gave it a shot, but as a mouseless user, I don't want to move my mouse to see the information.

**Comment by itsonlyjames** [comment]
Have to agree with @zhouhua, this would be unfeasible for users who—like me—remove the status bar in favour of stacked tabs.

<img width="864" alt="image" src="https://github.com/zhouhua/obsidian-sticky-headings/assets/6904599/f2cb3b04-9d57-41fd-833b-5085818cf399"> <br />

@TheMathGuyd might I suggest [Obsidian Switcher++](https://github.com/darlal/obsidian-switcher-plus) inwhich you could setup a shortcut for embedded symbol mode?

**Comment by itsonlyjames** [comment]
@zhouhua close this
