### ISSUE TITLE
Feature Request: Also render inline latex in sticky headings

### ISSUE THREAD

**Issue by FAL0258** [zhouhua/obsidian-sticky-headings#35]
I really love this plugin, but it would be great if the inline latex can also be shown when they are in headings.

I use this plugin with another plugin called [obsidian-quiet-outline](https://github.com/guopenghui/obsidian-quiet-outline/tree/master). While those inline latex can be rendered and shown properly in their plugin but not in sticky headings.

![image](https://github.com/user-attachments/assets/148ca4d1-4657-458d-b09b-92b3146f6789)

**Comment by zhouhua** [comment]
I added support for this case in the latest version.
