### ISSUE TITLE
[Fan sharing] Colorful background and float right styles

### ISSUE THREAD

**Issue by Aiuanyu** [zhouhua/obsidian-sticky-headings#37]
Hi Zhou Hua,

This is not an issue, but just that I would like to share a couple of [Obsidian Sticky Headings tweaks](https://gist.github.com/Aiuanyu/8539a8425435406ea79cbc64eaea6082).

<img width="1680" alt="截圖 2024-12-17 08 55 07" src="https://github.com/user-attachments/assets/60f3bebb-eb6b-4e50-8326-0b9237eef4e9" />

Thank you for creating this plugin!

**Comment by zhouhua** [comment]
Thanks for sharing! I just added a section in the project's README to collect some interesting styles.
