### ISSUE TITLE
Feature request: setting to change trigger-height for list updating during scroll

### ISSUE THREAD

**Issue by jmonroynieto** [zhouhua/obsidian-sticky-headings#39]
Currently, the plugin uses the rendering border of the workspace to select what heading is "focused" for the sticky list. I would like to change the triggering boundary's height so that it can guide me better. In general I scroll to keep the content I am working on above the middle line about one third of the way. In notes that have many short sections, such as a daily note, the current functionality makes it so that the condensed list is not reflective of my workflow, this decreases the usefulness of the plugin in many situations.

Do you believe this is something you would include as a setting?

**Comment by zhouhua** [comment]
https://github.com/zhouhua/obsidian-sticky-headings/releases/tag/2.1.2

I released a new version. I believe it may solve your problem.

**Comment by jmonroynieto** [comment]
Completely resolved. Thank you so much for having both pixel and percentage as options!
