### ISSUE TITLE
Clicked Heading Is Placed In Middle Of Screen Due To `setEphemeralState`

### ISSUE THREAD

**Issue by itsonlyjames** [zhouhua/obsidian-sticky-headings#5]
Not a bug, simply a dream. Love your plugin, it's almost perfect. I only wish that the clicked headings appeared at the top of the page and not in the middle. For me personally, it just feels so strange. 

I attempted many solutions such as `view.editor.scrollTo()` which I couldn't figure out an accurate way to calculate x and y coordinates. 

`view.editor.scrollIntoView()` works, however I can't seem to apply an offset so it is hidden underneath the sticky heading element.

Did you consider any other methods for scroll to? I will say, I do like that `setEphemeralState` also highlights the clicked title. Best of both worlds would be `setEphemeralState` with the option like `scrollIntoView` has that you can set to false or true and it either centers, or puts at the top: [Editor.scrollIntoView() method](https://docs.obsidian.md/Reference/TypeScript+API/Editor/scrollIntoView)

Maybe something we can add as an option, should we be able to figure out how to scroll it to the top of the page?

**Comment by zhouhua** [comment]
I think `scrollIntoView` might not be feasible. Due to Obsidian's virtual scrolling feature, headings that are outside the viewport might not exist in the DOM at all. I will look into other possible solutions.

**Comment by zhouhua** [comment]
I just released a new version. Please give it a try to see if it meets your needs.

**Comment by itsonlyjames** [comment]
@zhouhua you are an absolute genius mate, works perfect. Although highlight doesn't work, yet this isn't a deal breaker for me. Do you reckon it's worth making it a setting? Would some users prefer it to land in the middle?

**Comment by zhouhua** [comment]
I think highlighting might not be very necessary either. The effect similar to `scrollIntoView({block: 'nearest'})` is more intuitive, so I'll skip adding a setting option for it.
