### ISSUE TITLE
[Bug] Need to Reinstate Plugin at Correct Times

### ISSUE THREAD

**Issue by itsonlyjames** [zhouhua/obsidian-sticky-headings#9]
Have noticed this during dev, most changes don't initiate a new init and require a `reload app without saving` to get the new effects from changing settings.

**Comment by zhouhua** [comment]
I'm not entirely sure about the scenario you're referring to, as I haven't encountered this issue. However, you reminded me to add the logic for re-rendering headings when settings are changed.

https://github.com/zhouhua/obsidian-sticky-headings/commit/08da7bb015923a334fbd709ad59f4cdd1749b56e

**Comment by itsonlyjames** [comment]
Works perfect now 👌
